name: iOS build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Xcode version
        run: xcodebuild -version
      - name: Build
        run: |
          xcodebuild -project Pyramid.xcodeproj -scheme Pyramid -destination 'generic/platform=iOS Simulator' -configuration Debug CODE_SIGNING_ALLOWED=NO build
